language: node_js
services:
    - docker
install:
    - docker pull jboss/keycloak:11.0.2
    - docker images
    - node --version
before_script:
    - chmod + x $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh
    - docker-compose up -d keycloak    
script:
    - $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh

