dist: trusty
language: node_js
node_js:
  - "10.16.0"
services:
    - docker
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest    
install:
    - docker pull jboss/keycloak:11.0.2
    - docker images
    - node --version
before_script:
    - chmod +x $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh
    - chmod +x $TRAVIS_BUILD_DIR/webdriver/linux/geckodriver
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/webdriver/linux
    - docker-compose up -d keycloak
    - $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh
    - yarn
script:
    - npm run create-realm
