dist: trusty
language: node_js
node_js:
  - "10.16.0"
services:
    - docker
env:
  - MOZ_HEADLESS=1
install:
    - docker pull jboss/keycloak:11.0.2
    - docker images
    - node --version
before_script:
    - chmod +x $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh
    - docker-compose up -d keycloak
    - $TRAVIS_BUILD_DIR/keycloak/wait-for-keycloak.sh
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/webdriver/linux
script:
    - npm run create-realm
