version: '3.4'

services:

  keycloak:
    build: keycloak
    image: keycloak:ready
    container_name: keycloack
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./keycloak:/tmp/keycloak
